# Generated by Django 3.1.1 on 2020-11-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_auto_20201102_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='modificado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
