# Generated by Django 3.1.1 on 2020-11-02 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0005_auto_20201102_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='Subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foro.subcategoria', verbose_name='Subcategoria'),
        ),
    ]
