# Generated by Django 3.1.1 on 2020-10-06 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, unique_for_date='fecha_creacion')),
                ('subtitulo', models.CharField(max_length=75)),
                ('imagen', models.ImageField(upload_to=None)),
                ('cuerpo', models.TextField()),
                ('categoria', models.CharField(max_length=50)),
                ('etiquetas', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now_add=True)),
                ('fecha_eliminado', models.DateTimeField()),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuarios.usuario', verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'post',
                'ordering': ['-fecha_modificado'],
                'get_latest_by': '-fecha_modificado',
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['creado_por'], name='creador_por'),
        ),
    ]
