# Generated by Django 3.1.1 on 2020-10-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
    ]
