# Generated by Django 3.1.1 on 2020-10-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_codigos_activacio_usuarios'),
        ('blog', '0003_auto_20201006_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Creado por'),
        ),
    ]
