# Generated by Django 3.1.1 on 2020-10-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201012_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('GTS', 'Gran Turismo Sport'), ('GT7', 'Gran Turismo 7'), ('IR', 'iRacing'), ('PC2', 'Project Cars 2'), ('PC3', 'Project Cars 3'), ('RD4', 'Ride 4'), ('ATM', 'Automobilista 2'), ('RFC2', 'rFactor 2'), ('SR', 'SimRacing')], max_length=50),
        ),
    ]
