# Generated by Django 3.1.1 on 2020-10-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201027_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(upload_to='%Y/%m/%d/'),
        ),
    ]
