# Generated by Django 3.1.1 on 2020-10-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201027_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_eliminado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
