# Generated by Django 3.1.1 on 2020-11-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20201019_1105'),
        ('blog', '0008_auto_20201027_1148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Entrada',
        ),
        migrations.AlterModelOptions(
            name='entrada',
            options={'get_latest_by': '-fecha_modificado', 'ordering': ['-fecha_modificado'], 'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
    ]
