# Generated by Django 3.1.1 on 2020-10-06 11:47

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('usuarios', '0002_auto_20201006_1143'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
