# Generated by Django 3.1.1 on 2020-10-09 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0003_auto_20201006_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='status',
            new_name='rol',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='activo',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=50)),
                ('email_equipo', models.EmailField(max_length=254)),
                ('activo', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField()),
                ('pilotos', models.ManyToManyField(through='usuarios.Usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipo',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.equipo'),
        ),
    ]
