# Generated by Django 3.1.1 on 2020-10-09 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20201009_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='codigos_activacio_usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Codigo activacion',
                'verbose_name_plural': 'Codigos de activacion',
            },
        ),
    ]
