# Generated by Django 3.1.1 on 2020-10-19 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_codigos_activacio_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='registrado',
        ),
        migrations.AddField(
            model_name='usuario',
            name='confirmacion_activacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.equipo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('JE', 'Jefe de Equipo'), ('RP', 'Representante'), ('PV', 'Portavoz'), ('PI', 'Piloto')], default='JE', max_length=25),
        ),
        migrations.DeleteModel(
            name='codigos_activacio_usuarios',
        ),
    ]
